FROM alpine:3.7

# container deps
RUN apk update \
	&& apk add --no-cache --no-progress ca-certificates \
	&& rm -rf /var/cache/apk/* \
	&& mkdir -p /dfk

# container binary
ADD ./dtk-fetch.d-linux /dfk/fetch.d

# container configuration
WORKDIR /dfk
EXPOSE 8000
ENTRYPOINT /dfk/fetch.d

# CMD [""]